### ISSUE TITLE
npm install does not work : I did install globally to make it work npm install -g eslint

### ISSUE THREAD

**Issue by hiteshtara** [kuali/research-coi#18]
1233 silly lockFile 8ea7db77-custom-file-eslint-plugin-custom eslint-plugin-custom@file:eslint-plugin-custom
1234 error Error: No compatible version found: eslint-plugin-custom@'file:eslint-plugin-custom'
1234 error Valid install targets:
1234 error ["0.0.1","0.0.2","0.0.4","0.0.6"]
1234 error     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
1234 error     at /usr/share/npm/lib/cache.js:638:10
1234 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
1234 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
1234 error     at Object.oncomplete (fs.js:107:15)
1235 error If you need help, you may report this log at:
1235 error     http://github.com/isaacs/npm/issues
1235 error or email it to:
1235 error     npm-@googlegroups.com
1236 error System Linux 3.13.0-85-generic
1237 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
1238 error cwd /root/research-coi
1239 error node -v v0.10.25
1240 error npm -v 1.3.10

**Comment by tdurkin** [comment]
Hi - It looks like you're using an older version of node and npm. The readme.md file lists the 4.2.6 as the required version of node. The version of npm w/ 4.2.6 will work as well.
