### ISSUE TITLE
error when seeding

### ISSUE THREAD

**Issue by kgeis** [kuali/research-coi#2]
When seeding the database, I get the error:

    ReferenceError: Promise is not defined
        at insertInitialArchiveConfig (/opt/phoebe/research-coi-1.0.1/db/migration/seeds/A.js:282:10)
        at Promise.all.then.then.then.then.then.then.then.then.then.then.then.disclosures (/opt/phoebe/research-coi-1.0.1/db/migration/seeds/A.js:519:12)

**Comment by iambrandonn** [comment]
It looks like you're using an old version of Node.  You'll want to be on at least v0.12.7.  The next release will have updated docs stating such.

**Comment by kgeis** [comment]
Indeed, I am on an OS vendor package of v0.10.40. Thanks for the info.
